"""create sensors table 3

Revision ID: 1e747b0971aa
Revises: 314249fe7544
Create Date: 2026-06-20 09:43:15.956803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e747b0971aa'
down_revision: Union[str, Sequence[str], None] = '314249fe7544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('plot_id', sa.UUID(), nullable=False),
    sa.Column('esp32_id', sa.String(length=100), nullable=False),
    sa.Column('sensor_type', sa.String(length=50), nullable=False),
    sa.Column('depth_cm', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('battery_mv', sa.Integer(), nullable=True),
    sa.Column('last_reading', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('esp32_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    # ### end Alembic commands ###
