"""remove unique esp32 id

Revision ID: 6fc335ef3267
Revises: ad92fe9a4d80
Create Date: 2026-06-20 13:43:45.444293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc335ef3267'
down_revision: Union[str, Sequence[str], None] = 'ad92fe9a4d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sensors_esp32_id_key'), 'sensors', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('sensors_esp32_id_key'), 'sensors', ['esp32_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
