"""update users

Revision ID: 9546563f3ba4
Revises: 2e0229f6380a
Create Date: 2026-06-19 17:54:13.840177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9546563f3ba4'
down_revision: Union[str, Sequence[str], None] = '2e0229f6380a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Añadir la columna permitiendo NULL temporalmente
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))

    # 2. Rellenar los registros existentes
    op.execute("UPDATE users SET is_active = TRUE WHERE is_active IS NULL")

    # 3. Hacer la columna NOT NULL
    op.alter_column('users', 'is_active', nullable=False)

    # El resto de cambios generados por Alembic
    op.alter_column('farms', 'area_ha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('plots', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('plots', sa.Column('is_active', sa.Boolean(), nullable=False))



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('plots', 'is_active')
    op.drop_column('plots', 'name')
    op.alter_column('farms', 'area_ha',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
