"""add active flags 3

Revision ID: ad92fe9a4d80
Revises: f92b1f09fd44
Create Date: 2026-06-20 12:06:21.207814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad92fe9a4d80'
down_revision: Union[str, Sequence[str], None] = 'f92b1f09fd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'sensors',
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False)
    )
    op.alter_column('sensors', 'is_active', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensors', 'is_active')
    # ### end Alembic commands ###
