"""add active flags

Revision ID: f92b1f09fd44
Revises: 1e747b0971aa
Create Date: 2026-06-20 11:46:01.594996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f92b1f09fd44'
down_revision: Union[str, Sequence[str], None] = '1e747b0971aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Añadir columna con default temporal
    op.add_column(
        'farms',
        sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False)
    )

    # 2. Quitar el default si no lo quieres permanente
    op.alter_column('farms', 'is_active', server_default=None)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('farms', 'is_active')
    # ### end Alembic commands ###
